name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '4 2 * * 0'

defaults:
  run:
    shell: bash


jobs:
  build-env-kernel:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.kernel
          tags: ghcr.io/optix2000/bcachefs-deb:build-kernel

  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/optix2000/bcachefs-deb:build-kernel
    needs: build-env-kernel
    steps:
      - uses: actions/checkout@v3
      - run: make kernel
      - uses: actions/upload-artifact@v3
        with:
          name: linux.deb
          path: "*.deb"

  build-env-tools:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.tools
          tags: ghcr.io/optix2000/bcachefs-deb:build-tools

  build-tools:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/optix2000/bcachefs-deb:build-tools
    needs: build-env-tools
    steps:
      - uses: actions/checkout@v3
      - run: make tools
      - uses: actions/upload-artifact@v3
        with:
          name: bcachefs-tools.deb
          path: "*.deb"
